import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        border: "var(--border)",
        "primary-fixed-dim": "#c0c1ff",
        "surface-container-highest": "#d3e4fe",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb783",
        "tertiary-container": "#b55d00",
        "secondary-fixed": "#e9ddff",
        "on-surface-variant": "#464554",
        "outline": "#767586",
        "tertiary": "#904900",
        "on-secondary-container": "#fffbff",
        "surface-container-high": "#dce9ff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary-fixed-variant": "#5516be",
        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "primary": "#4648d4",
        "on-tertiary-fixed-variant": "#703700",
        "inverse-surface": "#213145",
        "surface-tint": "#494bd6",
        "on-primary-container": "#fffbff",
        "on-error": "#ffffff",
        "secondary-container": "#8455ef",
        "surface-variant": "#d3e4fe",
        "on-background": "#0b1c30",
        "secondary": "#6b38d4",
        "on-secondary-fixed": "#23005c",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fffbff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "on-primary": "#ffffff",
        "inverse-primary": "#c0c1ff",
        "secondary-fixed-dim": "#d0bcff",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#e1e0ff",
        "surface-dim": "#cbdbf5",
        "primary-container": "#6063ee",
        "on-primary-fixed-variant": "#2f2ebe",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#ffdcc5",
        "on-primary-fixed": "#07006c",
        "outline-variant": "#c7c4d7",
        "on-tertiary-fixed": "#301400",
        "error": "#ba1a1a"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xl": "2rem",
        "space-lg": "1.5rem",
        "margin": "2rem",
        "space-xs": "0.25rem",
        "gutter-sm": "1rem",
        "gutter-lg": "2rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "gutter": "1.5rem",
        "margin-lg": "3rem",
        "margin-sm": "1rem"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "headline-xl-mobile": ["Inter"],
        "headline-xl": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "code-md": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["15px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.005em", "fontWeight": "500" }],
        "body-sm": ["13px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.025em", "fontWeight": "700" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "label-sm": ["12px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "code-md": ["13px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "-0.005em", "fontWeight": "400" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
export default config
